# Generated by Django 6.1.2 on 2026-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatejob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
