# Generated by Django 6.1.2 on 2026-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatejob_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatejob',
            name='processed_certificates',
            field=models.IntegerField(default=0),
        ),
    ]
